version: '3.8'

services:
  ecovibe:
    build: .
    container_name: ecovibe-app
    restart: unless-stopped
    networks:
      - traefik_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      # Router configuration
      - "traefik.http.routers.ecovibe.rule=Host(`ecovibe.amejia.net`)"
      - "traefik.http.routers.ecovibe.entrypoints=websecure"
      - "traefik.http.routers.ecovibe.tls=true"
      - "traefik.http.routers.ecovibe.tls.certresolver=myresolver"
      # Service configuration
      - "traefik.http.services.ecovibe-service.loadbalancer.server.port=80"
      - "traefik.http.routers.ecovibe.service=ecovibe-service"
      # Compression middleware
      - "traefik.http.middlewares.ecovibe-compress.compress=true"
      - "traefik.http.middlewares.ecovibe-compress.compress.excludedContentTypes=image/png,image/jpeg,image/gif,image/webp,image/x-icon,application/pdf"
      - "traefik.http.middlewares.ecovibe-compress.compress.minResponseBodyBytes=1024"
      # Retry middleware
      - "traefik.http.middlewares.ecovibe-retry.retry.attempts=3"
      - "traefik.http.middlewares.ecovibe-retry.retry.initialInterval=100ms"
      # Headers middleware
      - "traefik.http.middlewares.ecovibe-headers.headers.customResponseHeaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.ecovibe-headers.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.ecovibe-headers.headers.customResponseHeaders.X-XSS-Protection=1; mode=block"
      # Combine middlewares
      - "traefik.http.routers.ecovibe.middlewares=ecovibe-compress,ecovibe-retry,ecovibe-headers"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.ecovibe-http.rule=Host(`ecovibe.amejia.net`)"
      - "traefik.http.routers.ecovibe-http.entrypoints=web"
      - "traefik.http.routers.ecovibe-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

networks:
  traefik_default:
    external: true